### ISSUE TITLE
Cache-Control issue

### ISSUE THREAD

**Issue by lawloretienne** [adavis/adept-android#1]
In this class :
https://github.com/adavis/adept-android/blob/retrofit2-cache/app/src/main/java/info/adavis/adeptandroid/di/Injector.java

It doesn't explicitly set the `public` directive in the `Cache-Control` header.  Isn't this necessary to get caching to work properly in offline mode?

**Comment by adavis** [comment]
Does it not work for you? It works for me. Do you have any logs or anything to show your issue? Thanks

**Comment by lawloretienne** [comment]
It doesn't work for me.  Here is what i tried

``` java
.addInterceptor(new Interceptor() {
    @Override
    public Response intercept(Chain chain) throws IOException {
        Request request = chain.request();
        // Add Cache Control only for GET methods
        if (request.method().equals("GET")) {
            if (NetworkUtility.isNetworkAvailable(MyApplication.getInstance())) {
                int maxAge = 60;
                // request = request.newBuilder().header("Cache-Control", "public, max-age=" + maxAge).build();
                CacheControl cacheControl = new CacheControl.Builder()
                    .maxAge(1, TimeUnit.MINUTES)
                    .noCache()
                    .build();

                request.newBuilder()
                    .cacheControl(cacheControl)
                    .build();
            } else {
                int maxStale = 60 * 60 * 24 * 7; // 1 week
                // request = request.newBuilder().header("Cache-Control", "public, only-if-cached, max-stale=" + maxStale).build();
                CacheControl cacheControl = new CacheControl.Builder()
                    .onlyIfCached()
                    .maxStale(7, TimeUnit.DAYS)
                    .build();

                request.newBuilder()
                    .cacheControl(cacheControl)
                    .build();
            }
        }
        return chain.proceed(request);
    }
})
```

**Comment by adavis** [comment]
In your `else` block can you try this:

```
else {
                CacheControl cacheControl = new CacheControl.Builder()
                    .maxStale(7, TimeUnit.DAYS)
                    .build();

                request = request.newBuilder()
                    .cacheControl(cacheControl)
                    .build();
            }
```

You didn't post your logs, so this is my best guess. You can also feel free to post a question on StackOverflow to reach out to a larger audience.

**Comment by lawloretienne** [comment]
So i tried removing `.onlyIfCached()` but it still doesn't work.  I get the error :

`HTTP FAILED: java.net.ConnectException: Failed to connect to <URL>`

Those commented out lines where i call `request.newBuilder().header()` in the comment above work for me.  But for some reason I cannot translate that to an equivalent `CacheControl.Builder`.

**Comment by adavis** [comment]
Did you set the request back like I did above?

```
request = request.newBuilder()
                    .cacheControl(cacheControl)
                    .build();
```

**Comment by lawloretienne** [comment]
Yes I tried creating the `CacheControl` object and setting it in `Request.Builder` but it didn't work. I got that same error.  

When i call the `request.newBuilder.header()` as I did above when the network connection is down I get the cached response and this warning 
`Warning: 110 HttpURLConnection "Response is stale"` which is to be expected.

I posted a variant of this question on StackOverflow :
http://stackoverflow.com/questions/37847831/how-do-you-set-up-the-cache-control-header-using-the-builder-pattern

**Comment by lawloretienne** [comment]
I just opened an issue in the OkHttp repo
https://github.com/square/okhttp/issues/2632
